export const PORTFOLIO = {
  company: 'Hannat Property Limited',
  companyNo: '16143184',
  director: 'Mrs Helen Binnie-Wise',
  address: '28 Davenport Avenue, Hessle, HU13 0RP',

  summary: {
    totalValue: 630000,
    totalMortgage: 334900,
    totalEquity: 295100,
    monthlyRent: 3680,
    monthlyMortgage: 1510,
    monthlyCosts: 363,
    monthlyNet: 1807,
    annualNet: 21684,
  },

  properties: [
    {
      id: 'p1',
      name: '11 Northfield Av',
      address: 'Hessle, HU13 9DJ',
      ownership: 'Personal',
      status: 'Let',
      yearBought: 2015,
      purchasePrice: 95000,
      currentValue: 150000,
      mortgage: 48000,
      monthlyRent: 850,
      monthlyPayment: 260,
      monthlyCosts: 80,
      gain: 55000,
      lender: 'Godiva',
      rate: null,
      fixEnd: null,
      epcRating: null,
      compliance: {
        eicr: { date: '16/07/2024', due: '16/07/2029', status: 'valid' },
        gas: { date: '17/06/2025', due: '17/06/2026', status: 'due-soon' },
        insurance: { insurer: 'LV=', policy: '21899512154', renewal: '12/03/2027', status: 'wrong-type', note: 'HOME policy not LANDLORD — call LV= 0330 678 5111' },
        coAlarm: 'yes',
        smokeAlarm: 'unconfirmed',
      },
      agent: 'Philip Bannister (Tenant Finder)',
      issues: ['Insurance wrong type — home not landlord', 'Smoke alarm unconfirmed'],
    },
    {
      id: 'p2',
      name: '3 Northfield Av',
      address: 'Hessle, HU13 9DJ',
      ownership: 'Personal',
      status: 'Let',
      yearBought: 2023,
      purchasePrice: 120000,
      currentValue: 135000,
      mortgage: 78900,
      monthlyRent: 730,
      monthlyPayment: 460,
      monthlyCosts: 80,
      gain: 15000,
      lender: 'Godiva',
      rate: null,
      fixEnd: null,
      epcRating: null,
      compliance: {
        eicr: { date: null, due: null, status: 'unknown' },
        gas: { date: '26/06/2025', due: '26/06/2026', status: 'due-soon' },
        insurance: { insurer: null, status: 'unknown' },
        coAlarm: 'unconfirmed',
        smokeAlarm: 'unconfirmed',
      },
      agent: 'Philip Bannister (Tenant Finder)',
      issues: ['CO/smoke alarms NA on cert — verify', 'EICR unknown', 'Insurance unknown'],
    },
    {
      id: 'p3',
      name: '7 Towerhill Mews',
      address: 'Hessle, HU13 0SR',
      ownership: 'Personal',
      status: 'Let',
      yearBought: 'Inherited',
      purchasePrice: 0,
      currentValue: 85000,
      mortgage: 60000,
      monthlyRent: 575,
      monthlyPayment: 127,
      monthlyCosts: 35,
      gain: 85000,
      lender: 'Godiva',
      rate: null,
      fixEnd: null,
      epcRating: null,
      tenant: { name: 'Ms Amanda Byrne', tel: '07450061542', depositScheme: 'DPS Custodial', depositAmount: 575 },
      compliance: {
        eicr: { date: '05/05/2021', due: '05/05/2026', status: 'urgent', note: 'Consumer unit install — 5yr inspection due' },
        gas: { date: '23/06/2025', due: '17/06/2026', status: 'due-soon' },
        insurance: { insurer: 'LV=', policy: '23000078388', premium: 211.20, renewal: '19/06/2026', status: 'valid' },
        coAlarm: 'yes',
        smokeAlarm: 'yes',
      },
      leasehold: { type: 'Leasehold', extensionCompleted: true, extensionYears: 100 },
      agent: 'Self-managed',
      issues: ['EICR book by May 2026', 'Gas + insurance both renew June'],
    },
    {
      id: 'p4',
      name: '31 Northfield Av',
      address: 'Hessle, HU13 9DL',
      ownership: 'Ltd Co',
      status: 'Completing',
      yearBought: 2026,
      purchasePrice: 100000,
      currentValue: 145000,
      mortgage: 75000,
      monthlyRent: 800,
      monthlyPayment: 340,
      monthlyCosts: 80,
      gain: 45000,
      lender: 'Godiva',
      rate: null,
      fixEnd: null,
      epcRating: null,
      cashAtCompletion: 30719,
      stampDuty: 5000,
      legalCosts: 2025,
      remortgage: { targetValue: 145000, maxAt75pct: 108750, currentMortgage: 75000, recyclable: 33750 },
      compliance: { eicr: { status: 'needed' }, gas: { status: 'needed' }, insurance: { status: 'needed' } },
      agent: null,
      issues: ['All compliance to arrange', 'ERC on Godiva rate TBC — upload mortgage offer'],
    },
    {
      id: 'p5',
      name: '602 Hotham Road',
      address: 'Hull, HU5 5LE',
      ownership: 'Ltd Co',
      status: 'Completing',
      yearBought: 2026,
      purchasePrice: 98500,
      currentValue: 120000,
      mortgage: 73875,
      monthlyRent: 725,
      monthlyPayment: 323,
      monthlyCosts: 80,
      gain: 21500,
      lender: 'Godiva',
      rate: 5.24,
      fixEnd: '31/07/2028',
      svrAfter: 6.54,
      epcRating: null,
      cashAtCompletion: 31064,
      stampDuty: 4775,
      legalCosts: 1864,
      erc: { rate1: 2.5, until1: '31/07/2027', rate2: 2.0, until2: '31/07/2028', maxErc: 1847, exitFee: 125 },
      remortgage: {
        targetValue: 120000, maxAt75pct: 90000, currentMortgage: 73875, recyclable: 16125,
        scenarioSep2026: { capital: 16125, erc: 1972, net: 14153 },
        scenarioAug2027: { capital: 16125, erc: 1603, net: 14522 },
        scenarioAug2028: { capital: 16125, erc: 0, net: 16125 },
      },
      compliance: { eicr: { status: 'needed' }, gas: { status: 'needed' }, insurance: { status: 'needed' } },
      agent: null,
      issues: ['All compliance to arrange', 'ERC £1,972 if remortgage before Aug 2027'],
    },
  ],

  legislation: [
    {
      id: 'rrb',
      name: "Renters' Rights Bill",
      status: 'Passing — Royal Assent 2025',
      impact: 'high',
      effectDate: 'Oct 2026 (est.)',
      items: [
        { severity: 'red', text: 'Section 21 abolished — no-fault evictions end. All 5 properties affected.' },
        { severity: 'red', text: 'All ASTs become periodic tenancies. Tenants can leave on 2 months notice.' },
        { severity: 'red', text: 'Landlord PRS Database registration mandatory before serving any notice.' },
        { severity: 'amber', text: 'Section 8 grounds strengthened — documented evidence required.' },
        { severity: 'amber', text: "Decent Homes Standard extended to PRS — damp, mould, hazards." },
        { severity: 'amber', text: "Awaab's Law — damp/mould investigations within 14 days." },
      ],
    },
    {
      id: 'epc',
      name: 'EPC Minimum C Requirement',
      status: 'Planned — 2028 new tenancies',
      impact: 'medium',
      effectDate: '2028 / 2030',
      items: [
        { severity: 'red', text: 'Properties rated D or E cannot be re-let after 2028 without works.' },
        { severity: 'amber', text: '11 Northfield (pre-1989, 35yr wiring) — EPC likely D. Check urgently.' },
        { severity: 'amber', text: '7 Towerhill — flat, potentially lower EPC. Assess now.' },
        { severity: 'green', text: '602 Hotham + 31 Northfield — refurb opportunity to build EPC C in now.' },
      ],
    },
    {
      id: 's24',
      name: 'Section 24 — Mortgage Interest Relief',
      status: 'In force',
      impact: 'ongoing',
      effectDate: 'Since 2020',
      items: [
        { severity: 'red', text: '11 Northfield, 3 Northfield, 7 Towerhill — 20% basic rate credit only.' },
        { severity: 'green', text: '31 Northfield + 602 Hotham (Ltd Co) — full mortgage interest deduction.' },
        { severity: 'amber', text: 'Consider incorporation strategy for personal properties — consult accountant.' },
      ],
    },
  ],

  contacts: [
    { role: 'Mortgage lender', name: 'Godiva Mortgages', tel: '0800 121 6162', note: 'Ref SPV-0764 (Hotham)' },
    { role: 'Mortgage broker', name: 'Chad Tyrrell-Styles', company: 'Mortgage 1st Ltd', tel: '07881291072', email: 'chad.tyrrell-styles@mortgage1st.co.uk' },
    { role: 'Solicitors', name: 'Gosschalks LLP', tel: '01482 324252', email: 'sml@gosschalks.co.uk', note: 'Ref 128806.1 & 128806.2' },
    { role: 'Letting agent', name: 'Philip Bannister & Co', tel: '01482 649777', email: 'info@philipbannister.co.uk', note: '11 & 3 Northfield — Tenant Finder' },
    { role: 'Gas engineer', name: 'Aron Barker', company: 'Ignite Yorkshire Gas Services', tel: '07525122051', note: 'Gas Safe 573310' },
    { role: 'Insurance', name: 'LV=', tel: '0330 678 5111', note: 'Policy 23000078388 (Towerhill) | 21899512154 (11 Northfield — WRONG TYPE)' },
  ],
}

export function fmt(n) {
  return '£' + Math.round(n).toLocaleString()
}

export function ltv(mortgage, value) {
  return ((mortgage / value) * 100).toFixed(1)
}

export function netYield(rent, mortgage, costs, value) {
  return (((rent - mortgage - costs) * 12 / value) * 100).toFixed(1)
}
